export enum EmployeeType {
    GET = "GET_EMPLOYEE",
    POST = "POST_EMPLOYEE",
    DETAIL = "DETAIL_EMPLOYEE",
    UPDATE = "UPDATE_EMPLOYEE",
    DELETE = "DELETE_EMPLOYEE",
    RESET = "RESET_EMPLOYEE",
  }
  